### ISSUE TITLE
[BUG] padding is not working with numpy 1.16

### ISSUE THREAD

**Issue by seyong92** [KAIST-MACLab/PyTSMod#13]
**Describe the bug**

x_padded = np.pad(x, ((0, 0), (left_pad, right_pad)))
TypeError: pad() missing 1 required positional argument: 'mode'

**To Reproduce**

Use TSM functions with numpy 1.16

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Python version: [e.g. Python 3.7.9]
 - Version [e.g. 0.3.1]

**Additional context**
